version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/api-expressjs-vm"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/api-functions-v4-azure-resource-management"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/api-inmemory"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/app-react-vite"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/azure-upload-file-to-storage/api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/azure-upload-file-to-storage/app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/ai-agents/ts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/ai-agents/js"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/ai-search"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/azure-openai-assistants/ts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/azure-openai-assistants/js"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/azure-sql/connect-and-query/ts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/azure-sql/connect-and-query/js"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/key-vault"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/openai"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/service-bus/ts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/quickstarts/storage"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/sdk/chained-credentials"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/test-api-functions-v4"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ts-boilerplate-common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/ts-boilerplate-esm"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/scripts"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
